loki:
  enabled: true
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: s3
      aws:
        s3: "s3://loki@minio-service.loki.svc.cluster.local/loki"
        access_key: myMinioAccessKey
        secret_access_key: myMinioSecretKey
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
  memcached:
    enabled: true
    batch_size: 100
    parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached.loki.svc.cluster.local
      service: memcached-client

